// src/renderer/src/view/FigmaUi/NewProjectDialog.tsx
import { useState } from "react";
import { motion } from "framer-motion";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "./ui/dialog";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Textarea } from "./ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Badge } from "./ui/badge";
import { Calendar } from "./ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "./ui/popover";
import { CalendarIcon, Plus, X } from "lucide-react";
import { format } from "date-fns";
import { zhCN } from "date-fns/locale";

interface NewProjectDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSubmit: (projectData: ProjectData) => void;
}

export interface ProjectData {
  id: string;
  name: string;
  description: string;
  team: string;
  status: string;
  priority: string;
  startDate: Date | undefined;
  endDate: Date | undefined;
  tags: string[];
  progress: number;
}

const teams = [
  "前端团队",
  "后端团队", 
  "移动团队",
  "架构团队",
  "设计团队",
  "测试团队"
];

const statuses = [
  "计划中",
  "开发中", 
  "测试",
  "活跃",
  "已完成",
  "暂停"
];

const priorities = [
  "低",
  "中",
  "高",
  "紧急"
];

export function NewProjectDialog({ open, onOpenChange, onSubmit }: NewProjectDialogProps) {
  const [formData, setFormData] = useState<Partial<ProjectData>>({
    name: "",
    description: "",
    team: "",
    status: "计划中",
    priority: "中",
    tags: [],
    progress: 0
  });
  
  const [newTag, setNewTag] = useState("");
  const [startDate, setStartDate] = useState<Date>();
  const [endDate, setEndDate] = useState<Date>();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.name || !formData.team) {
      return;
    }

    const projectData: ProjectData = {
      id: Date.now().toString(),
      name: formData.name,
      description: formData.description || "",
      team: formData.team,
      status: formData.status || "计划中", 
      priority: formData.priority || "中",
      startDate,
      endDate,
      tags: formData.tags || [],
      progress: formData.progress || 0
    };

    onSubmit(projectData);
    onOpenChange(false);
    
    // 重置表单
    setFormData({
      name: "",
      description: "",
      team: "",
      status: "计划中",
      priority: "中", 
      tags: [],
      progress: 0
    });
    setStartDate(undefined);
    setEndDate(undefined);
    setNewTag("");
  };

  const addTag = () => {
    if (newTag.trim() && !formData.tags?.includes(newTag.trim())) {
      setFormData(prev => ({
        ...prev,
        tags: [...(prev.tags || []), newTag.trim()]
      }));
      setNewTag("");
    }
  };

  const removeTag = (tagToRemove: string) => {
    setFormData(prev => ({
      ...prev,
      tags: prev.tags?.filter(tag => tag !== tagToRemove) || []
    }));
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>新建项目</DialogTitle>
          <DialogDescription>
            创建一个新的项目，填写项目的基本信息和配置。
          </DialogDescription>
        </DialogHeader>
        
        <motion.form
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          onSubmit={handleSubmit}
          className="space-y-6"
        >
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="name">项目名称 *</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                placeholder="输入项目名称"
                required
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="team">负责团队 *</Label>
              <Select
                value={formData.team}
                onValueChange={(value) => setFormData(prev => ({ ...prev, team: value }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder="选择负责团队" />
                </SelectTrigger>
                <SelectContent>
                  {teams.map((team) => (
                    <SelectItem key={team} value={team}>
                      {team}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">项目描述</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
              placeholder="详细描述项目内容和目标"
              rows={3}
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>项目状态</Label>
              <Select
                value={formData.status}
                onValueChange={(value) => setFormData(prev => ({ ...prev, status: value }))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {statuses.map((status) => (
                    <SelectItem key={status} value={status}>
                      {status}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            
            <div className="space-y-2">
              <Label>优先级</Label>
              <Select
                value={formData.priority}
                onValueChange={(value) => setFormData(prev => ({ ...prev, priority: value }))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {priorities.map((priority) => (
                    <SelectItem key={priority} value={priority}>
                      <span className={`${
                        priority === "紧急" ? "text-red-600" :
                        priority === "高" ? "text-orange-600" :
                        priority === "中" ? "text-yellow-600" : "text-green-600"
                      }`}>
                        {priority}
                      </span>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>开始日期</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    className="w-full justify-start text-left font-normal"
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {startDate ? format(startDate, "PPP", { locale: zhCN }) : "选择开始日期"}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0">
                  <Calendar
                    mode="single"
                    selected={startDate}
                    onSelect={setStartDate}
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
            </div>
            
            <div className="space-y-2">
              <Label>结束日期</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    className="w-full justify-start text-left font-normal"
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {endDate ? format(endDate, "PPP", { locale: zhCN }) : "选择结束日期"}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0">
                  <Calendar
                    mode="single"
                    selected={endDate}
                    onSelect={setEndDate}
                    initialFocus
                    disabled={(date) => startDate && date < startDate}
                  />
                </PopoverContent>
              </Popover>
            </div>
          </div>

          <div className="space-y-2">
            <Label>项目标签</Label>
            <div className="flex gap-2">
              <Input
                value={newTag}
                onChange={(e) => setNewTag(e.target.value)}
                placeholder="添加标签"
                onKeyPress={(e) => e.key === "Enter" && (e.preventDefault(), addTag())}
              />
              <Button type="button" variant="outline" size="sm" onClick={addTag}>
                <Plus className="h-4 w-4" />
              </Button>
            </div>
            {formData.tags && formData.tags.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-2">
                {formData.tags.map((tag) => (
                  <Badge key={tag} variant="secondary" className="flex items-center gap-1">
                    {tag}
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="h-auto p-0 w-4 h-4"
                      onClick={() => removeTag(tag)}
                    >
                      <X className="h-3 w-3" />
                    </Button>
                  </Badge>
                ))}
              </div>
            )}
          </div>

          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              取消
            </Button>
            <Button type="submit" disabled={!formData.name || !formData.team}>
              创建项目
            </Button>
          </DialogFooter>
        </motion.form>
      </DialogContent>
    </Dialog>
  );
}

// src/renderer/src/view/FigmaUi/NewProjectDialog.vue
<template>
  <div v-if="open" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
    <div class="bg-card max-w-2xl w-full max-h-[90vh] overflow-y-auto rounded-lg border shadow-lg mx-4">
      <div class="p-6 border-b">
        <h2 class="text-lg font-semibold">新建项目</h2>
        <p class="text-sm text-muted-foreground mt-1">
          创建一个新的项目，填写项目的基本信息和配置。
        </p>
      </div>
      
      <form @submit.prevent="handleSubmit" class="p-6 space-y-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="space-y-2">
            <label for="name" class="text-sm font-medium">项目名称 *</label>
            <input
              id="name"
              v-model="formData.name"
              class="flex h-10 w-full rounded-md border border-input bg-input-background px-3 py-2 text-sm"
              placeholder="输入项目名称"
              required
            />
          </div>
          
          <div class="space-y-2">
            <label class="text-sm font-medium">负责团队 *</label>
            <select
              v-model="formData.team"
              class="flex h-10 w-full rounded-md border border-input bg-input-background px-3 py-2 text-sm"
              required
            >
              <option value="">选择负责团队</option>
              <option v-for="team in teams" :key="team" :value="team">
                {{ team }}
              </option>
            </select>
          </div>
        </div>

        <div class="space-y-2">
          <label for="description" class="text-sm font-medium">项目描述</label>
          <textarea
            id="description"
            v-model="formData.description"
            class="flex min-h-[80px] w-full rounded-md border border-input bg-input-background px-3 py-2 text-sm"
            placeholder="详细描述项目内容和目标"
            rows="3"
          />
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="space-y-2">
            <label class="text-sm font-medium">项目状态</label>
            <select
              v-model="formData.status"
              class="flex h-10 w-full rounded-md border border-input bg-input-background px-3 py-2 text-sm"
            >
              <option v-for="status in statuses" :key="status" :value="status">
                {{ status }}
              </option>
            </select>
          </div>
          
          <div class="space-y-2">
            <label class="text-sm font-medium">优先级</label>
            <select
              v-model="formData.priority"
              class="flex h-10 w-full rounded-md border border-input bg-input-background px-3 py-2 text-sm"
            >
              <option v-for="priority in priorities" :key="priority" :value="priority">
                {{ priority }}
              </option>
            </select>
          </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="space-y-2">
            <label class="text-sm font-medium">开始日期</label>
            <input
              v-model="startDate"
              type="date"
              class="flex h-10 w-full rounded-md border border-input bg-input-background px-3 py-2 text-sm"
            />
          </div>
          
          <div class="space-y-2">
            <label class="text-sm font-medium">结束日期</label>
            <input
              v-model="endDate"
              type="date"
              class="flex h-10 w-full rounded-md border border-input bg-input-background px-3 py-2 text-sm"
              :min="startDate"
            />
          </div>
        </div>

        <div class="space-y-2">
          <label class="text-sm font-medium">项目标签</label>
          <div class="flex gap-2">
            <input
              v-model="newTag"
              class="flex h-10 flex-1 rounded-md border border-input bg-input-background px-3 py-2 text-sm"
              placeholder="添加标签"
              @keypress.enter.prevent="addTag"
            />
            <button
              type="button"
              @click="addTag"
              class="inline-flex items-center justify-center rounded-md border border-input bg-background px-3 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
            >
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
              </svg>
            </button>
          </div>
          <div v-if="formData.tags.length > 0" class="flex flex-wrap gap-2 mt-2">
            <span
              v-for="tag in formData.tags"
              :key="tag"
              class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold bg-secondary text-secondary-foreground gap-1"
            >
              {{ tag }}
              <button
                type="button"
                @click="removeTag(tag)"
                class="ml-1 h-3 w-3"
              >
                <svg class="h-3 w-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </span>
          </div>
        </div>

        <div class="flex justify-end gap-2 pt-4 border-t">
          <button
            type="button"
            @click="$emit('close')"
            class="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
          >
            取消
          </button>
          <button
            type="submit"
            :disabled="!formData.name || !formData.team"
            class="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            创建项目
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'

export interface ProjectData {
  id: string
  name: string
  description: string
  team: string
  status: string
  priority: string
  startDate: string | undefined
  endDate: string | undefined
  tags: string[]
  progress: number
}

interface Props {
  open: boolean
}

interface Emits {
  (e: 'close'): void
  (e: 'submit', projectData: ProjectData): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const teams = [
  "前端团队",
  "后端团队", 
  "移动团队",
  "架构团队",
  "设计团队",
  "测试团队"
]

const statuses = [
  "计划中",
  "开发中", 
  "测试",
  "活跃",
  "已完成",
  "暂停"
]

const priorities = [
  "低",
  "中",
  "高",
  "紧急"
]

const formData = reactive({
  name: "",
  description: "",
  team: "",
  status: "计划中",
  priority: "中",
  tags: [] as string[],
  progress: 0
})

const newTag = ref("")
const startDate = ref("")
const endDate = ref("")

const handleSubmit = () => {
  if (!formData.name || !formData.team) {
    return
  }

  const projectData: ProjectData = {
    id: Date.now().toString(),
    name: formData.name,
    description: formData.description,
    team: formData.team,
    status: formData.status,
    priority: formData.priority,
    startDate: startDate.value || undefined,
    endDate: endDate.value || undefined,
    tags: [...formData.tags],
    progress: formData.progress
  }

  emit('submit', projectData)
  
  // 重置表单
  Object.assign(formData, {
    name: "",
    description: "",
    team: "",
    status: "计划中",
    priority: "中",
    tags: [],
    progress: 0
  })
  startDate.value = ""
  endDate.value = ""
  newTag.value = ""
}

const addTag = () => {
  if (newTag.value.trim() && !formData.tags.includes(newTag.value.trim())) {
    formData.tags.push(newTag.value.trim())
    newTag.value = ""
  }
}

const removeTag = (tagToRemove: string) => {
  const index = formData.tags.indexOf(tagToRemove)
  if (index > -1) {
    formData.tags.splice(index, 1)
  }
}
</script>
