// src/renderer/src/view/FigmaUi/ProjectDetailsDialog.vue
<template>
  <div v-if="open && project" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
    <div class="bg-card max-w-4xl w-full max-h-[90vh] overflow-y-auto rounded-lg border shadow-lg mx-4">
      <div class="p-6 border-b">
        <div class="flex items-start justify-between">
          <div>
            <h2 class="text-xl font-semibold">{{ project.name }}</h2>
            <p class="text-sm text-muted-foreground mt-2">
              {{ project.description || "暂无项目描述" }}
            </p>
          </div>
          <div class="flex items-center gap-2">
            <button
              @click="$emit('edit', project)"
              class="inline-flex items-center justify-center rounded-md border border-input bg-background px-3 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
            >
              <svg class="h-4 w-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
              </svg>
              编辑
            </button>
            <button
              @click="showDeleteConfirm = true"
              class="inline-flex items-center justify-center rounded-md border border-input bg-background px-3 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground text-destructive"
            >
              <svg class="h-4 w-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
              删除
            </button>
          </div>
        </div>
      </div>

      <div class="p-6">
        <div class="border-b border-border">
          <nav class="-mb-px flex space-x-8">
            <button
              v-for="tab in tabs"
              :key="tab.id"
              @click="activeTab = tab.id"
              :class="[
                'py-2 px-1 border-b-2 font-medium text-sm',
                activeTab === tab.id
                  ? 'border-primary text-primary'
                  : 'border-transparent text-muted-foreground hover:text-foreground hover:border-gray-300'
              ]"
            >
              {{ tab.label }}
            </button>
          </nav>
        </div>

        <div class="mt-6">
          <!-- 项目概览 -->
          <div v-if="activeTab === 'overview'" class="space-y-4">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <div class="bg-card border rounded-lg p-4">
                <div class="flex items-center space-x-2">
                  <div :class="`w-3 h-3 rounded-full ${getStatusColor(project.status)}`" />
                  <div>
                    <p class="text-sm text-muted-foreground">状态</p>
                    <div class="flex items-center gap-1">
                      <component :is="getStatusIcon(project.status)" class="h-4 w-4" />
                      <span class="font-medium">{{ project.status }}</span>
                    </div>
                  </div>
                </div>
              </div>

              <div class="bg-card border rounded-lg p-4">
                <div class="flex items-center space-x-2">
                  <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197m13.5-9a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z" />
                  </svg>
                  <div>
                    <p class="text-sm text-muted-foreground">团队</p>
                    <p class="font-medium">{{ project.team }}</p>
                  </div>
                </div>
              </div>

              <div class="bg-card border rounded-lg p-4">
                <div class="flex items-center space-x-2">
                  <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
                  </svg>
                  <div>
                    <p class="text-sm text-muted-foreground">优先级</p>
                    <span :class="`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold ${getPriorityColor(project.priority)}`">
                      {{ project.priority }}
                    </span>
                  </div>
                </div>
              </div>

              <div class="bg-card border rounded-lg p-4">
                <div class="flex items-center space-x-2">
                  <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  <div>
                    <p class="text-sm text-muted-foreground">进度</p>
                    <p class="font-medium">{{ project.progress }}%</p>
                  </div>
                </div>
              </div>
            </div>

            <div class="bg-card border rounded-lg">
              <div class="p-4 border-b">
                <h3 class="font-semibold">项目进度</h3>
              </div>
              <div class="p-4">
                <div class="space-y-2">
                  <div class="flex justify-between text-sm">
                    <span>完成进度</span>
                    <span>{{ project.progress }}%</span>
                  </div>
                  <div class="w-full bg-secondary rounded-full h-3">
                    <div 
                      class="bg-primary h-3 rounded-full transition-all duration-300" 
                      :style="{ width: `${project.progress}%` }"
                    />
                  </div>
                </div>
              </div>
            </div>

            <div v-if="project.tags && project.tags.length > 0" class="bg-card border rounded-lg">
              <div class="p-4 border-b">
                <h3 class="font-semibold">项目标签</h3>
              </div>
              <div class="p-4">
                <div class="flex flex-wrap gap-2">
                  <span
                    v-for="tag in project.tags"
                    :key="tag"
                    class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold bg-secondary text-secondary-foreground"
                  >
                    {{ tag }}
                  </span>
                </div>
              </div>
            </div>
          </div>

          <!-- 进度管理 -->
          <div v-if="activeTab === 'progress'" class="space-y-4">
            <div class="bg-card border rounded-lg">
              <div class="p-4 border-b">
                <h3 class="font-semibold">进度管理</h3>
                <p class="text-sm text-muted-foreground">更新项目的完成进度</p>
              </div>
              <div class="p-4 space-y-4">
                <div class="space-y-2">
                  <div class="flex justify-between text-sm">
                    <span>当前进度</span>
                    <span>{{ project.progress }}%</span>
                  </div>
                  <div class="w-full bg-secondary rounded-full h-3">
                    <div 
                      class="bg-primary h-3 rounded-full transition-all duration-300" 
                      :style="{ width: `${project.progress}%` }"
                    />
                  </div>
                </div>
                
                <div class="grid grid-cols-2 md:grid-cols-4 gap-2">
                  <button
                    v-for="value in [25, 50, 75, 100]"
                    :key="value"
                    @click="updateProgress(value)"
                    :class="[
                      'px-3 py-2 text-sm font-medium rounded-md',
                      project.progress === value 
                        ? 'bg-primary text-primary-foreground' 
                        : 'border border-input bg-background hover:bg-accent hover:text-accent-foreground'
                    ]"
                  >
                    {{ value }}%
                  </button>
                </div>
              </div>
            </div>

            <!-- 里程碑 -->
            <div class="bg-card border rounded-lg">
              <div class="p-4 border-b">
                <h3 class="font-semibold">里程碑</h3>
              </div>
              <div class="p-4">
                <div class="space-y-4">
                  <div
                    v-for="(milestone, index) in milestones"
                    :key="index"
                    class="flex items-center space-x-3"
                  >
                    <div :class="`w-3 h-3 rounded-full ${project.progress >= milestone.threshold ? 'bg-green-500' : 'bg-gray-300'}`" />
                    <div class="flex-1">
                      <p class="font-medium">{{ milestone.title }}</p>
                      <p class="text-sm text-muted-foreground">{{ milestone.description }}</p>
                    </div>
                    <span :class="`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold ${
                      project.progress >= milestone.threshold 
                        ? 'bg-primary text-primary-foreground' 
                        : 'bg-secondary text-secondary-foreground'
                    }`">
                      {{ project.progress >= milestone.threshold ? "已完成" : "待完成" }}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- 详细信息 -->
          <div v-if="activeTab === 'details'" class="space-y-4">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div class="bg-card border rounded-lg">
                <div class="p-4 border-b">
                  <h3 class="font-semibold">时间安排</h3>
                </div>
                <div class="p-4 space-y-3">
                  <div class="flex items-center space-x-2">
                    <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                    <div>
                      <p class="text-sm text-muted-foreground">开始日期</p>
                      <p class="font-medium">{{ project.startDate || "未设置" }}</p>
                    </div>
                  </div>
                  <div class="flex items-center space-x-2">
                    <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                    <div>
                      <p class="text-sm text-muted-foreground">结束日期</p>
                      <p class="font-medium">{{ project.endDate || "未设置" }}</p>
                    </div>
                  </div>
                </div>
              </div>

              <div class="bg-card border rounded-lg">
                <div class="p-4 border-b">
                  <h3 class="font-semibold">项目信息</h3>
                </div>
                <div class="p-4 space-y-3">
                  <div>
                    <p class="text-sm text-muted-foreground">项目ID</p>
                    <p class="font-medium font-mono text-sm">{{ project.id }}</p>
                  </div>
                  <div>
                    <p class="text-sm text-muted-foreground">创建时间</p>
                    <p class="font-medium">{{ formatDate(project.id) }}</p>
                  </div>
                </div>
              </div>
            </div>

            <div v-if="project.description" class="bg-card border rounded-lg">
              <div class="p-4 border-b">
                <h3 class="font-semibold">项目描述</h3>
              </div>
              <div class="p-4">
                <p class="text-sm leading-6">{{ project.description }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="flex justify-end gap-2 p-6 border-t">
        <button
          @click="$emit('close')"
          class="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
        >
          关闭
        </button>
      </div>
    </div>

    <!-- 删除确认对话框 -->
    <div v-if="showDeleteConfirm" class="absolute inset-0 bg-black/50 flex items-center justify-center z-10">
      <div class="bg-white rounded-lg p-6 max-w-sm mx-4">
        <h3 class="font-medium mb-2">确认删除项目</h3>
        <p class="text-sm text-muted-foreground mb-4">
          确定要删除项目 "{{ project.name }}" 吗？此操作不可撤销。
        </p>
        <div class="flex justify-end gap-2">
          <button
            @click="showDeleteConfirm = false"
            class="inline-flex items-center justify-center rounded-md border border-input bg-background px-3 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
          >
            取消
          </button>
          <button
            @click="handleDelete"
            class="inline-flex items-center justify-center rounded-md bg-destructive px-3 py-2 text-sm font-medium text-destructive-foreground hover:bg-destructive/90"
          >
            删除
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import type { ProjectData } from './NewProjectDialog.vue'

interface Props {
  open: boolean
  project: ProjectData | null
}

interface Emits {
  (e: 'close'): void
  (e: 'edit', project: ProjectData): void
  (e: 'delete', projectId: string): void
  (e: 'updateProgress', projectId: string, progress: number): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const activeTab = ref('overview')
const showDeleteConfirm = ref(false)

const tabs = [
  { id: 'overview', label: '项目概览' },
  { id: 'progress', label: '进度管理' },
  { id: 'details', label: '详细信息' }
]

const milestones = [
  { threshold: 25, title: '项目启动', description: '完成项目规划和团队组建' },
  { threshold: 50, title: '开发阶段', description: '核心功能开发完成' },
  { threshold: 75, title: '测试阶段', description: '功能测试和优化完成' },
  { threshold: 100, title: '项目交付', description: '项目正式上线发布' }
]

const handleDelete = () => {
  if (props.project) {
    emit('delete', props.project.id)
    showDeleteConfirm.value = false
  }
}

const updateProgress = (progress: number) => {
  if (props.project) {
    emit('updateProgress', props.project.id, progress)
  }
}

const getStatusColor = (status: string) => {
  switch (status) {
    case "活跃": return "bg-green-500"
    case "开发中": return "bg-blue-500"
    case "测试": return "bg-yellow-500"
    case "已完成": return "bg-gray-500"
    case "暂停": return "bg-red-500"
    default: return "bg-gray-400"
  }
}

const getPriorityColor = (priority: string) => {
  switch (priority) {
    case "紧急": return "text-red-600 bg-red-50 border-red-200"
    case "高": return "text-orange-600 bg-orange-50 border-orange-200"
    case "中": return "text-yellow-600 bg-yellow-50 border-yellow-200"
    case "低": return "text-green-600 bg-green-50 border-green-200"
    default: return "text-gray-600 bg-gray-50 border-gray-200"
  }
}

const getStatusIcon = (status: string) => {
  // 返回简单的div，因为Vue中组件图标需要特殊处理
  return 'div'
}

const formatDate = (timestamp: string) => {
  return new Date(parseInt(timestamp)).toLocaleDateString('zh-CN')
}
</script>

// src/renderer/src/view/FigmaUi/ProjectDetailsDialog.tsx
import { useState } from "react";
import { motion } from "framer-motion";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "./ui/dialog";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Progress } from "./ui/progress";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { Separator } from "./ui/separator";
import { 
  Calendar, 
  Clock, 
  Users, 
  Target, 
  Edit, 
  Trash2, 
  Play, 
  Pause, 
  CheckCircle,
  AlertCircle
} from "lucide-react";
import { format } from "date-fns";
import { zhCN } from "date-fns/locale";
import { ProjectData } from "./NewProjectDialog";

interface ProjectDetailsDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  project: ProjectData | null;
  onEdit: (project: ProjectData) => void;
  onDelete: (projectId: string) => void;
  onUpdateProgress: (projectId: string, progress: number) => void;
}

export function ProjectDetailsDialog({ 
  open, 
  onOpenChange, 
  project, 
  onEdit, 
  onDelete,
  onUpdateProgress 
}: ProjectDetailsDialogProps) {
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  if (!project) return null;

  const handleDelete = () => {
    onDelete(project.id);
    setShowDeleteConfirm(false);
    onOpenChange(false);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "活跃": return "bg-green-500";
      case "开发中": return "bg-blue-500";
      case "测试": return "bg-yellow-500";
      case "已完成": return "bg-gray-500";
      case "暂停": return "bg-red-500";
      default: return "bg-gray-400";
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "紧急": return "text-red-600 bg-red-50";
      case "高": return "text-orange-600 bg-orange-50";
      case "中": return "text-yellow-600 bg-yellow-50";
      case "低": return "text-green-600 bg-green-50";
      default: return "text-gray-600 bg-gray-50";
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "活跃": return <Play className="h-4 w-4" />;
      case "开发中": return <Clock className="h-4 w-4" />;
      case "测试": return <AlertCircle className="h-4 w-4" />;
      case "已完成": return <CheckCircle className="h-4 w-4" />;
      case "暂停": return <Pause className="h-4 w-4" />;
      default: return <Target className="h-4 w-4" />;
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-start justify-between">
            <div>
              <DialogTitle className="text-xl">{project.name}</DialogTitle>
              <DialogDescription className="mt-2">
                {project.description || "暂无项目描述"}
              </DialogDescription>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={() => onEdit(project)}>
                <Edit className="h-4 w-4 mr-2" />
                编辑
              </Button>
              <Button 
                variant="outline" 
                size="sm" 
                onClick={() => setShowDeleteConfirm(true)}
                className="text-destructive hover:text-destructive"
              >
                <Trash2 className="h-4 w-4 mr-2" />
                删除
              </Button>
            </div>
          </div>
        </DialogHeader>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
        >
          <Tabs defaultValue="overview" className="space-y-4">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="overview">项目概览</TabsTrigger>
              <TabsTrigger value="progress">进度管理</TabsTrigger>
              <TabsTrigger value="details">详细信息</TabsTrigger>
            </TabsList>

            <TabsContent value="overview" className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <Card>
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-2">
                      <div className={`w-3 h-3 rounded-full ${getStatusColor(project.status)}`} />
                      <div>
                        <p className="text-sm text-muted-foreground">状态</p>
                        <div className="flex items-center gap-1">
                          {getStatusIcon(project.status)}
                          <span className="font-medium">{project.status}</span>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-2">
                      <Users className="h-4 w-4 text-muted-foreground" />
                      <div>
                        <p className="text-sm text-muted-foreground">团队</p>
                        <p className="font-medium">{project.team}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-2">
                      <Target className="h-4 w-4 text-muted-foreground" />
                      <div>
                        <p className="text-sm text-muted-foreground">优先级</p>
                        <Badge className={getPriorityColor(project.priority)}>
                          {project.priority}
                        </Badge>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-2">
                      <Calendar className="h-4 w-4 text-muted-foreground" />
                      <div>
                        <p className="text-sm text-muted-foreground">进度</p>
                        <p className="font-medium">{project.progress}%</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>

              <Card>
                <CardHeader>
                  <CardTitle>项目进度</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm">
                      <span>完成进度</span>
                      <span>{project.progress}%</span>
                    </div>
                    <Progress value={project.progress} className="h-3" />
                  </div>
                </CardContent>
              </Card>

              {project.tags && project.tags.length > 0 && (
                <Card>
                  <CardHeader>
                    <CardTitle>项目标签</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="flex flex-wrap gap-2">
                      {project.tags.map((tag) => (
                        <Badge key={tag} variant="secondary">
                          {tag}
                        </Badge>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              )}
            </TabsContent>

            <TabsContent value="progress" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>进度管理</CardTitle>
                  <DialogDescription>
                    更新项目的完成进度
                  </DialogDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm">
                      <span>当前进度</span>
                      <span>{project.progress}%</span>
                    </div>
                    <Progress value={project.progress} className="h-3" />
                  </div>
                  
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                    {[25, 50, 75, 100].map((value) => (
                      <Button
                        key={value}
                        variant={project.progress === value ? "default" : "outline"}
                        size="sm"
                        onClick={() => onUpdateProgress(project.id, value)}
                      >
                        {value}%
                      </Button>
                    ))}
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>里程碑</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="flex items-center space-x-3">
                      <div className={`w-3 h-3 rounded-full ${project.progress >= 25 ? 'bg-green-500' : 'bg-gray-300'}`} />
                      <div className="flex-1">
                        <p className="font-medium">项目启动</p>
                        <p className="text-sm text-muted-foreground">完成项目规划和团队组建</p>
                      </div>
                      <Badge variant={project.progress >= 25 ? "default" : "secondary"}>
                        {project.progress >= 25 ? "已完成" : "待完成"}
                      </Badge>
                    </div>
                    
                    <Separator />
                    
                    <div className="flex items-center space-x-3">
                      <div className={`w-3 h-3 rounded-full ${project.progress >= 50 ? 'bg-green-500' : 'bg-gray-300'}`} />
                      <div className="flex-1">
                        <p className="font-medium">开发阶段</p>
                        <p className="text-sm text-muted-foreground">核心功能开发完成</p>
                      </div>
                      <Badge variant={project.progress >= 50 ? "default" : "secondary"}>
                        {project.progress >= 50 ? "已完成" : "待完成"}
                      </Badge>
                    </div>
                    
                    <Separator />
                    
                    <div className="flex items-center space-x-3">
                      <div className={`w-3 h-3 rounded-full ${project.progress >= 75 ? 'bg-green-500' : 'bg-gray-300'}`} />
                      <div className="flex-1">
                        <p className="font-medium">测试阶段</p>
                        <p className="text-sm text-muted-foreground">功能测试和优化完成</p>
                      </div>
                      <Badge variant={project.progress >= 75 ? "default" : "secondary"}>
                        {project.progress >= 75 ? "已完成" : "待完成"}
                      </Badge>
                    </div>
                    
                    <Separator />
                    
                    <div className="flex items-center space-x-3">
                      <div className={`w-3 h-3 rounded-full ${project.progress >= 100 ? 'bg-green-500' : 'bg-gray-300'}`} />
                      <div className="flex-1">
                        <p className="font-medium">项目交付</p>
                        <p className="text-sm text-muted-foreground">项目正式上线发布</p>
                      </div>
                      <Badge variant={project.progress >= 100 ? "default" : "secondary"}>
                        {project.progress >= 100 ? "已完成" : "待完成"}
                      </Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="details" className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Card>
                  <CardHeader>
                    <CardTitle>时间安排</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div className="flex items-center space-x-2">
                      <Calendar className="h-4 w-4 text-muted-foreground" />
                      <div>
                        <p className="text-sm text-muted-foreground">开始日期</p>
                        <p className="font-medium">
                          {project.startDate 
                            ? format(project.startDate, "PPP", { locale: zhCN })
                            : "未设置"
                          }
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Calendar className="h-4 w-4 text-muted-foreground" />
                      <div>
                        <p className="text-sm text-muted-foreground">结束日期</p>
                        <p className="font-medium">
                          {project.endDate 
                            ? format(project.endDate, "PPP", { locale: zhCN })
                            : "未设置"
                          }
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>项目信息</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div>
                      <p className="text-sm text-muted-foreground">项目ID</p>
                      <p className="font-medium font-mono text-sm">{project.id}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">创建时间</p>
                      <p className="font-medium">
                        {format(new Date(parseInt(project.id)), "PPP", { locale: zhCN })}
                      </p>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {project.description && (
                <Card>
                  <CardHeader>
                    <CardTitle>项目描述</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm leading-6">{project.description}</p>
                  </CardContent>
                </Card>
              )}
            </TabsContent>
          </Tabs>
        </motion.div>

        {showDeleteConfirm && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="absolute inset-0 bg-black/50 flex items-center justify-center z-10"
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              className="bg-white rounded-lg p-6 max-w-sm mx-4"
            >
              <h3 className="font-medium mb-2">确认删除项目</h3>
              <p className="text-sm text-muted-foreground mb-4">
                确定要删除项目 "{project.name}" 吗？此操作不可撤销。
              </p>
              <div className="flex justify-end gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setShowDeleteConfirm(false)}
                >
                  取消
                </Button>
                <Button
                  variant="destructive"
                  size="sm"
                  onClick={handleDelete}
                >
                  删除
                </Button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </DialogContent>
    </Dialog>
  );
}
